package element;

import exceptions.NullFieldException;
import exceptions.WrongFieldException;

import java.util.Date;

/** Class of the object stored in the collection.
 * @author Kirill Markov
 * @version 1.0*/
public class SpaceMarine implements CollectionPart {
    /**
     * Unique id of the element. Must be greater than 0. Must be generated automatically(not by user).
     */
    private final long
            id; // Значение поля должно быть больше 0, Значение этого поля должно быть уникальным,
    // Значение этого поля должно генерироваться автоматически
    /** Element's name. Cannot be null or empty and cannot contain commas. */
    private String name; // Поле не может быть null, Строка не может быть пустой
    /** Element's coordinates({@link element.Coordinates}). Cannot be null. */
    private Coordinates coordinates; // Поле не может быть null
    /**
     * Element's creation date. Cannot be null. Must be generated automatically(not by user). Pattern:
     * EEE MMM dd kk:mm:ss z yyyy."
     */
    private final java.util.Date
            creationDate; // Поле не может быть null, Значение этого поля должно генерироваться
    // автоматически
    /** Value of element's health. Can be null. Must be greater than 0. */
    private Double health; // Поле может быть null, Значение поля должно быть больше 0
    /** Value of element's heartCount. Must be greater than 0 and less than or equal to 3. */
    private int heartCount; // Значение поля должно быть больше 0, Максимальное значение поля: 3
    /** category({@link element.AstartesCategory}) of the element. Can be null. */
    private AstartesCategory category; // Поле может быть null
    /** meleeWeapon({@link element.MeleeWeapon}) of the element. Can be null. */
    private MeleeWeapon meleeWeapon; // Поле может быть null
    /** chapter({@link element.Chapter}) of the element. Cannot be null. */
    private Chapter chapter; // Поле не может быть null

    /**
     * Constructs a new SpaceMarine object. Used <b>only for reading collection from CSV file</b>.
     *
     * @param name Element's name.
     * @param coordinates Element's coordinates.
     * @param health Value of element's health.
     * @param heartCount Value of element's heartCount.
     * @param category category of the element.
     * @param meleeWeapon meleeWeapon of the element.
     * @param chapter chapter of the element.
     * @param id Element's id.
     * @param creationDate Element's creationDate.
     * @throws exceptions.WrongFieldException if id or health or heart count is less than or equal to
     *     0 or heart count is greater than 3
     * @throws exceptions.NullFieldException if name or coordinates or chapter is null.
     */
    public SpaceMarine(
            String name,
            Coordinates coordinates,
            Double health,
            int heartCount,
            AstartesCategory category,
            MeleeWeapon meleeWeapon,
            Chapter chapter,
            long id,
            Date creationDate) {
        if (name == null || name.equals("")) {
            throw new NullFieldException("name");
        }
        if (coordinates == null) {
            throw new NullFieldException("coordinates");
        }
        if (health != null && health <= 0) {
            throw new WrongFieldException("The value of the health field must be greater than 0");
        }
        if (heartCount <= 0 || heartCount > 3) {
            throw new WrongFieldException(
                    "The value of the heartCount field must be greater than 0.The value of the heartCount field must be less than or equal to 3.");
        }
        if (chapter == null) {
            throw new NullFieldException("chapter");
        }
        if (id <= 0) {
            throw new WrongFieldException("The value of the id field must be greater than 0");
        }
        this.id = id;
        this.name = name;
        this.coordinates = coordinates;
        this.creationDate = creationDate;
        this.health = health;
        this.heartCount = heartCount;
        this.category = category;
        this.meleeWeapon = meleeWeapon;
        this.chapter = chapter;
    }

    /**
     * Constructs a new SpaceMarine object. Used to create element <b>by user</b> because id and
     * creation date are autogenerated.
     *
     * @param name Element's name. Cannot be null or empty and cannot contain commas.
     * @param coordinates Element's coordinates({@link element.Coordinates}). Cannot be null.
     * @param health Value of element's health. Can be null. Must be greater than 0.
     * @param heartCount Value of element's heartCount. Must be greater than 0 and less than or
     *     equal to 3.
     * @param category category({@link element.AstartesCategory}) of the element. Can be null.
     * @param meleeWeapon meleeWeapon({@link element.MeleeWeapon}) of the element. Can be null.
     * @param chapter chapter({@link element.Chapter}) of the element. Cannot be null.
     * @throws exceptions.WrongFieldException if health or heart count is less than or equal to
     * 0 or heart count is greater than 3
     * @throws exceptions.NullFieldException if name or coordinates or chapter is null.
     */
    public SpaceMarine(
            String name,
            Coordinates coordinates,
            Double health,
            int heartCount,
            AstartesCategory category,
            MeleeWeapon meleeWeapon,
            Chapter chapter) {
        this(
                name,
                coordinates,
                health,
                heartCount,
                category,
                meleeWeapon,
                chapter,
                Math.abs(new Date().getTime()),
                new Date());
    }

    @Override
    public long getId() {
        return id;
    }

    @Override
    public String getName() {
        return name;
    }

    @Override
    public void setName(String name) {
        this.name = name;
    }

    @Override
    public Coordinates getCoordinates() {
        return coordinates;
    }

    @Override
    public void setCoordinates(Coordinates coordinates) {
        this.coordinates = coordinates;
    }

    @Override
    public Date getCreationDate() {
        return creationDate;
    }

    @Override
    public Double getHealth() {
        return health;
    }

    @Override
    public void setHealth(Double health) {
        this.health = health;
    }

    @Override
    public int getHeartCount() {
        return heartCount;
    }

    @Override
    public void setHeartCount(int heartCount) {
        this.heartCount = heartCount;
    }

    @Override
    public AstartesCategory getCategory() {
        return category;
    }

    @Override
    public void setCategory(AstartesCategory category) {
        this.category = category;
    }

    @Override
    public MeleeWeapon getMeleeWeapon() {
        return meleeWeapon;
    }

    @Override
    public void setMeleeWeapon(MeleeWeapon meleeWeapon) {
        this.meleeWeapon = meleeWeapon;
    }

    @Override
    public Chapter getChapter() {
        return chapter;
    }

    @Override
    public void setChapter(Chapter chapter) {
        this.chapter = chapter;
    }

    /** Basically compares names of the elements. {@inheritDoc} */
    @Override
    public int compareTo(CollectionPart o) {
        return this.getName().compareTo(o.getName());
    }

    @Override
    public String toLineCSV() {
        String strCategory = "";
        if (this.category != null) {
            strCategory = this.category.toString();
        }
        String strMeleeWeapon = "";
        if (this.meleeWeapon != null) {
            strMeleeWeapon = this.meleeWeapon.toString();
        }
        String strHealth = "";
        if (this.health != null) {
            strHealth = this.health.toString();
        }
        return String.format(
                "%s,%d,%d,%s,%d,%s,%s,%s,%d,%d,%s",
                this.name,
                this.coordinates.getX(),
                this.coordinates.getY(),
                strHealth.replace(',', '.'),
                this.heartCount,
                strCategory,
                strMeleeWeapon,
                this.chapter.getName(),
                this.chapter.getMarinesCount(),
                this.id,
                this.creationDate);
    }

    @Override
    public String toString() {
        return String.format(
                "id: %d%n"
                        + "name: %s%n"
                        + "coordinates:%n"
                        + "   x: %d%n"
                        + "   y: %d%n"
                        + "creationDate: %s%n"
                        + "health: %f%n"
                        + "heartCount: %d%n"
                        + "category: %s%n"
                        + "meleeWeapon: %s%n"
                        + "chapter:%n"
                        + "   name: %s%n"
                        + "   marinesCount: %d%n%n",
                this.id,
                this.name,
                this.coordinates.getX(),
                this.coordinates.getY(),
                this.creationDate,
                this.health,
                this.heartCount,
                this.category,
                this.meleeWeapon,
                this.chapter.getName(),
                this.chapter.getMarinesCount());
    }
}